import{i,S as d}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();async function m(n){const s=`https://pixabay.com/api/?key=43045926-d10eb038526040017b5fd39ad&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const e=await fetch(s);if(!e.ok)throw new Error("Network response was not ok");return(await e.json()).hits}catch(e){throw console.error("Error fetching data: ",e),e}}function g(n){const r=document.querySelector(".gallery-img");if(r.innerHTML="",n.length===0){i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=n.map(({webformatURL:e,largeImageURL:t,tags:a,likes:c,views:l,comments:f,downloads:u})=>`<a href="${t}" class="gallery-item" data-lightbox="gallery">
    <img src="${e}" alt="${a}" />
    <div class="info">
      <p><strong>Likes:</strong> ${c}</p>
      <p><strong>Views:</strong> ${l}</p>
      <p><strong>Comments:</strong> ${f}</p>
      <p><strong>Downloads:</strong> ${u}</p>
    </div>
  </a>`).join("");r.innerHTML=o,new d(".gallery-item",{captionsData:"alt"}).refresh()}document.getElementById("form").addEventListener("submit",async n=>{n.preventDefault();const r=document.getElementById("query").value.trim();if(!r){alert("Please enter a search term");return}try{const o=await m(r);g(o)}catch(o){console.error("Failed to fetch images:",o),i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}});
//# sourceMappingURL=commonHelpers.js.map
